import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Insightify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark" className="scroll-smooth">
      <body className={inter.className}>
        {/* <Script
          src={`https://www.googletagmanager.com/gtag/js?id=G-FDP3HFP9HB`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || [];
  			function gtag(){dataLayer.push(arguments);}
  			gtag('js', new Date());
gtag('config', 'G-FDP3HFP9HB');`}
        </Script> */}
        <div>
          <Toaster />
        </div>
        {children}
      </body>
    </html>
  );
}
